### PR TITLE
Fixes custom timestamp formatting

### LINKED ISSUE #4: winston.format.timestamp({ format: <YYYY-MM> }) doesn't work with format parameter (issue with solution)
Hi!,

i discover that:

./logform/timestamp.js:

14 module.exports = format(function (info, opts) {                                                                                                                                    
15   if (opts.format) {
16     info.timestamp = typeof opts.format === 'function'
17       ? opts.format()                                                                                                                                                              
18       : formatDate(**new Date()**, opts.format); // <<<<<<<<<<<<<<<<<<<<< **the solution!**
19   }
20     
21   if (!info.timestamp) {                                                                                                                                                           
22     info.timestamp = new Date().toISOString();                                                                                                                                     
23   }                                                                                                                                                                                
24                                                                                                                                                                                    
25   if (opts.alias) {
26     info[opts.alias] = info.timestamp;
27   }                                                                                                                                                                                
28                                                                                                                                                                                    
29   return info;
30 });

Sorry if i dont respect de standards to report an issue.

### PR DESCRIPTION
**Pull request by MartinMuzatko**
Fixes #4

### CODE REVIEW

**Comment by MartinMuzatko** [comment]
@indexzero Would be nice to merge this :)

**Comment by MartinMuzatko** [comment]
Pretty please

**Comment by indexzero** [comment]
Would be great to add test coverage to prevent this regression in the future. Have a minute to write some tests? 😇

**Comment by MartinMuzatko** [comment]
:hushed: I've never written a test in mocha/assume 😞 
I'll try my best, I guess. But don't expect too much.

**Comment by MartinMuzatko** [comment]
image
Are the tests supposed to pass?

And is populist an npm package I have to install? it is not part of the packages

**Comment by nfantone** [comment]
I'm interested in this getting merged. Any way I could help, @indexzero?

@MartinMuzatko Is right here: `populist` hasn't been explicitly declared on `devDependencies`.

**Comment by indexzero** [comment]
Closing as a duplicate of #11. Appreciate your effort, but tests are quite important.

**Pull request closed without merging**
