### PR TITLE
In CliFormat use cli levels (not npm levels).

### PR DESCRIPTION
**Pull request by MatrixFrog**
This fixes https://github.com/winstonjs/winston/issues/2053

### CODE REVIEW

**Review by DABH — COMMENTED** [review]
Could this be a breaking change?  Can we union these two sets of levels so that there’s no chance of this being a break and change, and then fully do the switchover in the next major version? Or, is the proposed set of levels a strict superset of the current set of levels?

**Comment by MatrixFrog** [comment]
Hm, good question. The levels are https://github.com/winstonjs/triple-beam/blob/master/config/cli.js and https://github.com/winstonjs/triple-beam/blob/master/config/npm.js

The only one that's in npm but not in cli is `http`. But also, `verbose` and `debug` are in the opposite order between the two.

I'm not really sure if it could be a breaking change but I guess it's possible.

**Comment by MatrixFrog** [comment]
I guess my intuition is that it's unlikely to be a breaking change unless someone is expecting a very specific format, down to the exact number of spaces, in their logs. But obviously it's your call. Happy to change it, or I checked the box so you can change it too.

**Review by DABH — APPROVED** [review]
Let's go ahead and try this.  Thank you!

**Pull request merged**
