### PR TITLE
Add tsconfig.json (fixes #19)

### LINKED ISSUE #19: Typescript warning in logform/index.d.ts: "use --declaration --outDir"
I'm seeing this warning while importing `winston`. (With typescript 2.6.2).

```shell
WARNING in ./node_modules/logform/index.d.ts
Module build failed: Error: Typescript emitted no output for /Users/aneil/code/myapp/web/app-backend/node_modules/logform/index.d.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader (/Users/aneil/code/myapp/web/app-backend/node_modules/ts-loader/dist/index.js:47:15)
    at Object.loader (/Users/aneil/code/myapp/web/app-backend/node_modules/ts-loader/dist/index.js:29:12)
 @ ./node_modules/logform ^\.\/.*$
 @ ./node_modules/logform/index.js
 @ ./node_modules/winston/lib/winston.js
 @ ./src/logger.ts
```

```javascript
// src/logger.ts

const winston =  require('winston');

export const log = winston.createLogger({
  transports: [
    new winston.transports.Console(),
  ]
});
```

### PR DESCRIPTION
**Pull request by DABH**

### CODE REVIEW

**Comment by aneilbaboo** [comment]
Thanks, @DABH!

Is this ready to merge?

**Comment by DABH** [comment]
We'll merge it tomorrow morning -- hope it fixes your issue.

**Comment by aneilbaboo** [comment]
Great, thanks again. I'll let you know how it goes.

**Comment by aneilbaboo** [comment]
Oh dear. Looks like I'm still seeing the problem:

```shell
WARNING in ./node_modules/logform/index.d.ts
Module build failed: Error: Typescript emitted no output for .../node_modules/logform/index.d.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader (.../node_modules/ts-loader/dist/index.js:39:15)
    at Object.loader (.../node_modules/ts-loader/dist/index.js:21:12)
 @ ./node_modules/logform sync ^\.\/.*$
 @ ./node_modules/logform/index.js
 @ ./node_modules/winston/lib/winston.js
 @ ./src/logger.ts
 @ ./src/server/handler.ts

WARNING in ./node_modules/logform/CHANGELOG.md
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| # CHANGELOG
|
| ### 1.4.1
 @ ./node_modules/logform sync ^\.\/.*$
 @ ./node_modules/logform/index.js
 @ ./node_modules/winston/lib/winston.js
 @ ./src/logger.ts
 @ ./src/server/handler.ts

WARNING in ./node_modules/logform/README.md
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
| # logform
|
| An mutable object-based log format designed for chaining & objectMode streams.
 @ ./node_modules/logform sync ^\.\/.*$
 @ ./node_modules/logform/index.js
 @ ./node_modules/winston/lib/winston.js
 @ ./src/logger.ts
 @ ./src/server/handler.ts
```

After some inspection, I think this may be related to how Webpack deals with dynamic requires. I think it's the `exposeFormat` method in `index.js` which is causing the problem.

Webpack attempts to require all files when it finds a dynamic require.

**Comment by DABH** [comment]
Yeah, seems like it's a webpack issue.  You should be picking up browser.js not index.js (the former is browser-safe, no dynamic requires).  Any ideas why not?  Could just be a bad webpack config I suspect.  If the issue persists, maybe you can put up a MWE we can look at?  We definitely are planning to support browsers/bundlers in v3 so would be great to make sure this works.

**Comment by aneilbaboo** [comment]
Webpack 4.5 fixes the problem. Sorry for taking up time with this.

**Comment by DABH** [comment]
Good to know!  Glad it’s working :)

**Comment by aneilbaboo** [comment]
Just discovered my solution didn't work.  I masked the problem with another change, and had runtime errors. 

I just submitted a PR which fixes the problem. #24

**Pull request merged**
