### PR TITLE
TransformableInfo should support symbols as keys

### PR DESCRIPTION
**Pull request by dancrumb**
Being able to use a Symbol as a key for TransformableInfo makes it easier to create cleaner transforms.

The current typing forbids this, so this change enables it.

### CODE REVIEW

**Comment by dscalzi** [comment]
cc @wbt please merge this, it has been a problem for over two years. It's incredibly annoying to have to copy the same typings patch on every project that uses winston.

This project looks largely unmaintained, but this is a zero-effort solution to a frustrating issue.

**Review by dscalzi — APPROVED** [review]

**Comment by dscalzi** [comment]
reference: #111 #114

**Comment by wbt** [comment]
> cc @wbt please merge this, it has been a problem for over two years. It's incredibly annoying to have to copy the same typings patch on every project that uses winston.

FYI, that claim seems a bit less than truthful given that TS support for this is only a year and a half old. 

> this is a zero-effort solution to a frustrating issue.

Also not quite true according to the folks complaining at #244.

**Comment by dscalzi** [comment]
The issue was first reported more than 2 years ago and never received a response.

**Comment by dscalzi** [comment]
See #15 ...

**Comment by wbt** [comment]
Support for using symbols as index types, which is what this specific PR is about, has only been released for a year and a half.  
That is what's causing problems at #244 - it's too recent a feature in TS.

**Pull request merged**
