### PR TITLE
Fixing issue #250

### PR DESCRIPTION
**Pull request by petarpetrov88**
A simple solution to Issue [#250](https://github.com/winstonjs/logform/issues/250) and [#244](https://github.com/winstonjs/logform/issues/244)

### CODE REVIEW

**Comment by wbt** [comment]
Why is it useful to disallow symbols as keys and allow numbers instead?

**Comment by petarpetrov88** [comment]
> Why is it useful to disallow symbols as keys and allow numbers instead? See #240.

Sorry, there is none. I've fixed it.

**Comment by wbt** [comment]
On a quick read, changing from a colon to `in` also seems to create a mapped type with all possible strings/symbols - can you describe more about the motivation for that change?

**Comment by petarpetrov88** [comment]
> On a quick read, changing from a colon to `in` also seems to create a mapped type with all possible strings/symbols - can you describe more about the motivation for that change?

The previous version doesn't work in TS 3 and above.

**Comment by petarpetrov88** [comment]
I've changed it to string | number, because the error i was getting was "An index signature parameter type must be 'string' or 'number'."

**Comment by wbt** [comment]
> I've changed it to string | number, because the error i was getting was "An index signature parameter type must be 'string' or 'number'."

In what version of TS?

**Comment by petarpetrov88** [comment]
> > I've changed it to string | number, because the error i was getting was "An index signature parameter type must be 'string' or 'number'."
> 
> In what version of TS?

You can see [here](https://www.typescriptlang.org/play?ts=3.3.3#code/C4TwDgpgBAKgTgQwHYGcBmB7OBbBAjAGwgEklMoBeKAbwCgoGoBtAawhCgEskoVg5uAcygAfKEgCu2PBDgBdAFxRkIANy0AvlABkNelCIA3CASV8BSQeobYIKFAkEQlK9RvW1uwWWgQBjaHhkdCxcQhIyDABhDAIpHjoGIxMzfiFrKFt7R2dlJDV9VnZUi2ExSWlZRTyC9yA) that from 3.3.3 till 4.5.5 the old version is throwing an error.

**Comment by wbt** [comment]
> You can see [here](https://www.typescriptlang.org/play?ts=3.3.3#code/C4TwDgpgBAKgTgQwHYGcBmB7OBbBAjAGwgEklMoBeKAbwCgoGoBtAawhCgEskoVg5uAcygAfKEgCu2PBDgBdAFxRkIANy0AvlABkNelCIA3CASV8BSQeobYIKFAkEQlK9RvW1uwWWgQBjaHhkdCxcQhIyDABhDAIpHjoGIxMzfiFrKFt7R2dlJDV9VnZUi2ExSWlZRTyC9yA) that from 3.3.3 till 4.5.5 the old version is throwing an error.

I don't see that, from [v4.4.4](https://www.typescriptlang.org/play?ts=4.4.4#code/C4TwDgpgBAKgTgQwHYGcBmB7OBbBAjAGwgEklMoBeKAbwCgoGoBtAawhCgEskoVg5uAcygAfKEgCu2PBDgBdAFxRkIANy0AvlABkNelCIA3CASV8BSQeobYIKFAkEQlK9RvW1uwWWgQBjaHhkdCxcQhIyDABhDAIpHjoGIxMzfiFrKFt7R2dlJDV9VnZUi2ExSWlZRTyC9yA) or [v4.5.5](https://www.typescriptlang.org/play?ts=4.5.5#code/C4TwDgpgBAKgTgQwHYGcBmB7OBbBAjAGwgEklMoBeKAbwCgoGoBtAawhCgEskoVg5uAcygAfKEgCu2PBDgBdAFxRkIANy0AvlABkNelCIA3CASV8BSQeobYIKFAkEQlK9RvW1uwWWgQBjaHhkdCxcQhIyDABhDAIpHjoGIxMzfiFrKFt7R2dlJDV9VnZUi2ExSWlZRTyC9yA) 

I also think you're still missing the point of #240.

**Comment by petarpetrov88** [comment]
> > You can see [here](https://www.typescriptlang.org/play?ts=3.3.3#code/C4TwDgpgBAKgTgQwHYGcBmB7OBbBAjAGwgEklMoBeKAbwCgoGoBtAawhCgEskoVg5uAcygAfKEgCu2PBDgBdAFxRkIANy0AvlABkNelCIA3CASV8BSQeobYIKFAkEQlK9RvW1uwWWgQBjaHhkdCxcQhIyDABhDAIpHjoGIxMzfiFrKFt7R2dlJDV9VnZUi2ExSWlZRTyC9yA) that from 3.3.3 till 4.5.5 the old version is throwing an error.
> 
> I don't see that, from [v4.4.4](https://www.typescriptlang.org/play?ts=4.4.4#code/C4TwDgpgBAKgTgQwHYGcBmB7OBbBAjAGwgEklMoBeKAbwCgoGoBtAawhCgEskoVg5uAcygAfKEgCu2PBDgBdAFxRkIANy0AvlABkNelCIA3CASV8BSQeobYIKFAkEQlK9RvW1uwWWgQBjaHhkdCxcQhIyDABhDAIpHjoGIxMzfiFrKFt7R2dlJDV9VnZUi2ExSWlZRTyC9yA) or [v4.5.5](https://www.typescriptlang.org/play?ts=4.5.5#code/C4TwDgpgBAKgTgQwHYGcBmB7OBbBAjAGwgEklMoBeKAbwCgoGoBtAawhCgEskoVg5uAcygAfKEgCu2PBDgBdAFxRkIANy0AvlABkNelCIA3CASV8BSQeobYIKFAkEQlK9RvW1uwWWgQBjaHhkdCxcQhIyDABhDAIpHjoGIxMzfiFrKFt7R2dlJDV9VnZUi2ExSWlZRTyC9yA).
> 
> I also think you're still missing the point of #240.

I don't see how I miss it. I've changed the type to string | symbol so this won't affect it. Regarding the TS version, yes the problem is present till v4.3.5. It's late for me and I'm tired.

**Comment by wbt** [comment]
The current version of logform requires TS 4.4+, as discussed in #244.  If for whatever reason someone can't use a reasonably modern version of TypeScript they can [pin Logform to an out-of-date version](https://github.com/winstonjs/logform/issues/244#issuecomment-1420903011) since they are apparently fine pinning to out-of-date versions of dependencies.  There's not really interest in breaking things for people who are running current versions in order to make things better for a few folks who insist on keeping to older technology, especially in the absence of any automated regression testing against a range of older versions.  Thanks for your efforts.

**Pull request closed without merging**
