### PR TITLE
Resolve TypeError

### PR DESCRIPTION
**Pull request by adampweb**
Issue represented here: https://github.com/winstonjs/winston/issues/2327

### CODE REVIEW

**Comment by wbt** [comment]
Try running npm i and committing the changes to the lockfile.

**Comment by DABH** [comment]
@adampweb can you update .GitHub/workflows/CI.yaml to run node 16/18/20 instead of 12/14/16?  That should fix this - thanks!

**Comment by DABH** [comment]
@adampweb see above comment ^^

**Comment by adampweb** [comment]
TypeScript now only runs on Node.js 14.17 and later. Why are PRs being tested with version 12?

**Comment by DABH** [comment]
> @adampweb can you update .GitHub/workflows/CI.yaml to run node 16/18/20 instead of 12/14/16? That should fix this - thanks!

@adampweb ^^

**Pull request closed without merging**
